version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ~/.kube:/root/.kube
    environment:
      - PYTHONPATH=/app
      - KUBERNETES_CONTEXT=docker-desktop
    ports:
      - "8080:8080"
      - "9090:9090"