version: '3.8'

services:
  detector:
    build: .
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - KUBERNETES_SERVICE_HOST=${K8S_HOST}
      - KUBERNETES_SERVICE_PORT=${K8S_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-devsecops_db}
      POSTGRES_USER: ${DB_USER:-db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-db_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: