application_name: ai-devsecops-framework
version: 1.0.0
description: Configuration settings for the AI-augmented DevSecOps framework.
logging:
  level: INFO
  file: logs/app.log
database:
  host: localhost
  port: 5432
  user: db_user
  password: db_password
  name: devsecops_db
security:
  enable_https: true
  ssl_cert_path: /path/to/cert.pem
  ssl_key_path: /path/to/key.pem
  api_fuzzing:
    max_requests_per_endpoint: 100
    timeout_seconds: 30
    attack_patterns_path: config/attack_patterns.yaml
    severity_levels:
      - CRITICAL
      - HIGH
      - MEDIUM
      - LOW
    test_types:
      - injection
      - xss
      - auth_bypass
      - rate_limit
    retries: 3
    concurrent_tests: 5
api:
  base_url: /api/v1
  timeout: 30
features:
  anomaly_detection: true
  predictive_threat_detection: true
  automated_response: true

model:
  lstm:
    units: 64
    sequence_length: 100
    threshold: 0.85
    
security:
  scan_interval: 300
  max_retries: 3
  alert_threshold: 0.9
  
monitoring:
  prometheus_port: 9090
  grafana_port: 3000
  metrics_retention: 30d